"""
app/modules/cv_analysis.py

CV Analysis Module — intent: cv_analysis

Extracts text from a student's CV (PDF / DOCX via fileUrl or file_bytes),
then uses the LLM to produce structured professional feedback:

  - Extracted: skills, projects, experience
  - Gaps:      missing skills, weak areas
  - Advice:    course/improvement recommendations

Output: bullet-point professional feedback (human-readable + structured data).

Architecture rules
------------------
- AI extracts + analyses. Backend is NOT called here — this is purely AI-driven
  analysis. No backend tool is required for CV analysis.
"""
from __future__ import annotations

import io
import re
from typing import Any, Dict, Optional

import httpx

from app.agents.schemas import AgentInput, AgentOutput
from app.core.logging import logger

_DEFAULT_MODEL = "openai/gpt-4o-mini"


# ── File extraction helpers ────────────────────────────────────────────────────

def _extract_pdf(data: bytes) -> str:
    try:
        from pdfminer.high_level import extract_text
        return extract_text(io.BytesIO(data)) or ""
    except Exception:
        pass
    try:
        import pypdf
        reader = pypdf.PdfReader(io.BytesIO(data))
        return "\n".join(page.extract_text() or "" for page in reader.pages)
    except Exception as exc:
        logger.warning("CVAnalysisModule: PDF extraction failed — %s", exc)
        return ""


def _extract_docx(data: bytes) -> str:
    try:
        import docx
        doc = docx.Document(io.BytesIO(data))
        return "\n".join(p.text for p in doc.paragraphs if p.text)
    except Exception as exc:
        logger.warning("CVAnalysisModule: DOCX extraction failed — %s", exc)
        return ""


def _extract_text(data: bytes, filename: str) -> str:
    name = (filename or "").lower()
    if name.endswith(".pdf"):
        return _extract_pdf(data)
    if name.endswith(".docx"):
        return _extract_docx(data)
    return data.decode("utf-8", errors="ignore")


def _extract_url(message: str) -> Optional[str]:
    match = re.search(r"https?://\S+", message)
    return match.group(0).rstrip(".,)>\"'") if match else None


async def _download(url: str, auth_header: Optional[str]) -> bytes:
    headers: Dict[str, str] = {}
    if auth_header:
        headers["Authorization"] = auth_header
    async with httpx.AsyncClient(follow_redirects=True, timeout=30.0) as client:
        resp = await client.get(url, headers=headers)
        resp.raise_for_status()
        return resp.content


# ── CV Analysis system prompt ──────────────────────────────────────────────────

_CV_SYSTEM_PROMPT = """You are an expert career advisor and technical recruiter specialising in
software engineering and technology roles for university graduates.

Your task is to analyse the CV text provided and return a structured response
with the following sections (use markdown bold headers):

**1. Extracted Profile**
- List the candidate's technical skills (programming languages, frameworks, tools)
- List notable projects with a one-line description each
- Summarise professional/internship experience

**2. Identified Gaps & Weak Areas**
- Identify missing skills that are common in the job market for their level
- Flag any weak areas: e.g. no GitHub link, no deployed projects, vague descriptions

**3. Recommendations**
- Suggest 3-5 specific courses or certifications (mention platforms: Coursera, Udemy, etc.)
- Suggest 2-3 concrete improvements to the CV itself
- Provide one actionable study/project plan for the next 3 months

Keep your response concise (max 400 words), professional, and encouraging.
Respond in the same language as the CV content."""


class CVAnalysisModule:
    """
    Downloads a student CV, extracts its text, and returns professional
    feedback generated by the LLM.

    File source priority:
      1. context["file_bytes"] + context["file_name"]
      2. context["fileUrl"] or fileUrl found in the user message
    """

    def __init__(self, model_router, backend_client=None):
        self.model_router   = model_router
        self.backend_client = backend_client  # not used; kept for constructor symmetry

    async def run(self, agent_input: AgentInput, plan=None) -> AgentOutput:
        ctx      = agent_input.context or {}
        model_id = ctx.get("selected_model") or _DEFAULT_MODEL
        message  = agent_input.message or ""

        # ── 1. Obtain CV text ─────────────────────────────────────────────────
        cv_text, file_name = await self._get_cv_text(agent_input, ctx, message)

        if not cv_text or not cv_text.strip():
            return AgentOutput(
                status="failed",
                response=(
                    "I couldn't extract text from your CV. "
                    "Please ensure you provide a valid PDF or DOCX file URL, "
                    "or paste the CV content directly in your message."
                ),
            )

        logger.info(
            "CVAnalysisModule: extracted %d chars from '%s'", len(cv_text), file_name
        )

        # ── 2. Direct text in message? Use it too ────────────────────────────
        # If the CV text is short and message is long, inject message as supplement
        analysis_text = cv_text[:5_000]  # safe token limit

        # ── 3. LLM analysis ───────────────────────────────────────────────────
        feedback = await self.model_router.generate(
            prompt=(
                f"Please analyse the following CV and provide structured feedback:\n\n"
                f"CV CONTENT:\n{analysis_text}"
            ),
            system_instruction=_CV_SYSTEM_PROMPT,
            model_id=model_id,
        )

        if not feedback:
            return AgentOutput(
                status="failed",
                response="The CV analysis could not be completed. Please try again.",
            )

        return AgentOutput(
            status="success",
            response=feedback,
            data={
                "module":     "CVAnalysisModule",
                "file_name":  file_name,
                "char_count": len(cv_text),
                "model_used": model_id,
            },
        )

    # ──────────────────────────────────────────────────────────────────────────
    #  Helpers
    # ──────────────────────────────────────────────────────────────────────────

    async def _get_cv_text(
        self,
        agent_input: AgentInput,
        ctx: Dict[str, Any],
        message: str,
    ) -> tuple[str, str]:
        """
        Returns (cv_text, file_name).

        Priority:
          1. file_bytes in context (already downloaded by upload handler)
          2. fileUrl in context or message (download now)
          3. raw message text as fallback (user pasted CV inline)
        """
        # 1. In-memory bytes
        file_bytes: Optional[bytes] = ctx.get("file_bytes")
        file_name: str = ctx.get("file_name", "cv.pdf")
        if file_bytes:
            return _extract_text(file_bytes, file_name), file_name

        # 2. URL in context or message
        file_url: Optional[str] = ctx.get("fileUrl") or ctx.get("file_url") or _extract_url(message)
        if file_url:
            # Guess file name from URL
            url_path = file_url.split("?")[0]
            file_name = url_path.split("/")[-1] or "cv.pdf"
            logger.info("CVAnalysisModule: downloading CV from %s", file_url)
            try:
                raw = await _download(file_url, agent_input.auth_header)
                return _extract_text(raw, file_name), file_name
            except Exception as exc:
                logger.error("CVAnalysisModule: download failed — %s", exc)
                return "", file_name

        # 3. Raw message text fallback (user pasted CV inline)
        if len(message) > 200:
            logger.info("CVAnalysisModule: using raw message as CV text (len=%d)", len(message))
            return message, "inline_cv.txt"

        return "", "unknown"
