from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field

class AgentInput(BaseModel):
    """Initial input provided to an Agent to start processing."""
    message: str = Field(..., description="The user's raw message or goal")
    user_id: Optional[str] = Field(None, description="The origin user's ID for context")
    auth_header: Optional[str] = Field(None, description="Forwarded JWT for backend auth")
    context: Dict[str, Any] = Field(default_factory=dict, description="Any existing context for the agent")

class AgentOutput(BaseModel):
    """The final structured output from an Agent after processing."""
    status: str = Field(default="success", description="Status of the agent execution")
    response: str = Field(..., description="Natural language response or final summary")
    data: Optional[Dict[str, Any]] = Field(None, description="Any raw data to pass continuously")

class ExecutionStep(BaseModel):
    """A single tool execution step within a broader plan."""
    step_id: int = Field(..., description="Order of execution")
    tool_name: str = Field(..., description="Name of the backend tool to execute")
    parameters: Dict[str, Any] = Field(default_factory=dict, description="Parameters mapped for the tool")
    depends_on: List[int] = Field(default_factory=list, description="List of step_ids this step depends on")

class ExecutionPlan(BaseModel):
    """A structured plan of ExecutionSteps generated by the Planner Agent."""
    goal_summary: str = Field(..., description="Summary of what the plan aims to achieve")
    steps: List[ExecutionStep] = Field(default_factory=list, description="Ordered steps for execution")
    is_executable: bool = Field(default=True, description="Whether the plan is valid and can be run")
