from typing import Any, Dict, List, Literal, Optional
from pydantic import BaseModel, Field

class AgentInput(BaseModel):
    """Initial input provided to an Agent to start processing."""
    message: str = Field(..., description="The user's raw message or goal")
    user_id: Optional[str] = Field(None, description="The origin user's ID for context")
    auth_header: Optional[str] = Field(None, description="Forwarded JWT for backend auth")
    context: Dict[str, Any] = Field(default_factory=dict, description="Any existing context for the agent")

class AgentOutput(BaseModel):
    """The final structured output from an Agent after processing."""
    status: str = Field(default="success", description="Status of the agent execution")
    response: str = Field(..., description="Natural language response or final summary")
    data: Optional[Dict[str, Any]] = Field(None, description="Any raw data to pass continuously")

class ExecutionStep(BaseModel):
    """A single execution step within a broader plan."""
    step_id: int = Field(..., description="Order of execution")
    action: str = Field(..., description="Type of action: 'tool', 'model', or 'agent_module'")
    tool_name: Optional[str] = Field(None, description="Name of the backend tool to execute, if action is 'tool'")
    model_name: Optional[str] = Field(None, description="Name of the model to use, if action is 'model'")
    module_name: Optional[str] = Field(None, description="Name of the agent module, if action is 'agent_module'")
    input_payload: Dict[str, Any] = Field(default_factory=dict, description="Input payload or parameters mapped for the action")
    depends_on: List[int] = Field(default_factory=list, description="List of step_ids this step depends on")
    condition: Optional[str] = Field(None, description="Optional condition to evaluate before executing this step")

class ExamParams(BaseModel):
    """Typed parameters extracted from a doctor's exam-generation request."""
    collegeName: Optional[str] = Field(None, description="Name of the college/university")
    departmentName: Optional[str] = Field(None, description="Academic department name")
    batchName: Optional[str] = Field(None, description="Student batch / cohort name")
    subjectName: Optional[str] = Field(None, description="Name of the subject for the exam")
    numberOfQuestions: Optional[int] = Field(None, description="Total number of questions to generate")
    examType: Optional[Literal["midterm", "final"]] = Field(None, description="Type of exam: midterm or final")
    variationMode: Optional[Literal["same_for_all", "different_per_student"]] = Field(
        None, description="Whether all students receive the same exam or individual variations"
    )
    subjectOfferingId: Optional[str] = Field(
        None,
        description="Backend ID for the subject offering. If absent, ResolveSubjectOffering must run first.",
    )


class PreExecutionStep(BaseModel):
    """
    A prerequisite tool call that must be satisfied before the main
    ExecutionPlan steps can run (e.g. resolving an unknown ID).
    """
    tool: str = Field(..., description="Tool name to invoke, e.g. 'ResolveSubjectOffering'")
    reason: str = Field(..., description="Human-readable explanation of why this step is required")
    input_payload: Dict[str, Any] = Field(
        default_factory=dict,
        description="Parameters to forward to the tool",
    )


class ExecutionPlan(BaseModel):
    """A structured plan of ExecutionSteps generated by the Planner Agent."""
    goal_summary: str = Field(..., description="Summary of what the plan aims to achieve")
    intent: Optional[str] = Field(None, description="High-level intent label, e.g. 'generate_exam'")
    steps: List[ExecutionStep] = Field(default_factory=list, description="Ordered steps for execution")
    is_executable: bool = Field(default=True, description="Whether the plan is valid and can be run")
    exam_params: Optional[ExamParams] = Field(
        None,
        description="Populated when intent is 'generate_exam'; holds all exam configuration.",
    )
    pre_execution_steps: List[PreExecutionStep] = Field(
        default_factory=list,
        description="Tool calls required before the main steps (e.g. ResolveSubjectOffering).",
    )
